# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-20 05:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_sub', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventsub',
            name='email',
            field=models.EmailField(help_text=b'Please enter your email', max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='eventsub',
            name='name',
            field=models.CharField(help_text=b'Please enter your name', max_length=50),
        ),
    ]
