# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-20 06:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_sub', '0002_auto_20180220_0515'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventsub',
            options={'ordering': ['-subscribed_at']},
        ),
        migrations.AddField(
            model_name='eventsub',
            name='subscribed_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
